Associa streamers à playlists
TreinaDev/stream-beta pull request #57
Opened 2021-11-24 03:08 UTC by daiaventureira

2021-11-24 15:22 UTC, joaorsalmeida requested changes
Precisamos aumentar a resiliência do teste principal da feature entregue aqui.

2021-11-24 15:22 UTC, joaorsalmeida commented on spec/system/admin_creates_playlist_spec.rb
> +    create(:streamer, name: 'Fulaninho')
Em testes assim seria ideal ter mais de um `streamer` e garantir que somente um deles foi associado. Do jeito que esse teste foi escrito é possivel editar o código para vincular todos streamers à playlist no código do controller e o teste segue funcionando, concordam?

2021-11-24 15:25 UTC, daiaventureira commented on spec/system/admin_creates_playlist_spec.rb
> +    create(:streamer, name: 'Fulaninho')
João, fizemos assim pois entendemos que pode haver uma playlist com muitos streamers, não?
Mas no meu entendimento poder que pode haver uma playlist com videos de todos os streamers por ex. 
 Temos então que garantir que esse streamer tem um vídeo na playlist?.

2021-11-24 21:56 UTC, paulo-castellan commented
@joaorsalmeida , resolvemos a questão dos testes, o conflito em relação ao db/schema.rb pensei que seria resolvido com um rails db:migrate, porém não foi resolvido, como devo agir

2021-11-25 17:41 UTC, joaorsalmeida approved these changes

2021-11-25 17:48 UTC, merged