Adicionada Área do Assinante com Histórico e relação de Planos
TreinaDev/stream-beta pull request #69
Opened 2021-11-25 21:19 UTC by Donads

Resolve: #68

2021-11-26 12:48 UTC, joaorsalmeida requested changes
Acho que nesse PR tem comentários com pendências de outros PRs já encerrados. Podem confirmar?

2021-11-26 12:48 UTC, joaorsalmeida commented on app/controllers/user/dashboard_controller.rb
> +      # TODO: Alterar quando o PR #67 for liberado
Esse PR já foi fechado né? Bora 'resolver' esses comentários então?!

2021-11-26 12:48 UTC, joaorsalmeida commented on spec/system/user/user_acesses_purchase_history_spec.rb
> +      user.subscription_plans += [plan1]
Aqui você pode usar o `<<`

2021-11-26 18:23 UTC, Donads commented on app/controllers/user/dashboard_controller.rb
> +      # TODO: Alterar quando o PR #67 for liberado
Feito o/

2021-11-26 18:23 UTC, Donads commented on spec/system/user/user_acesses_purchase_history_spec.rb
> +      user.subscription_plans += [plan1]
Boa idéia!

2021-11-26 18:26 UTC, Donads commented
> Acho que nesse PR tem comentários com pendências de outros PRs já encerrados. Podem confirmar?

@joaorsalmeida Tudo resolvido o/

2021-11-29 16:39 UTC, joaorsalmeida approved these changes

2021-11-29 16:40 UTC, merged